plugins:
  - serverless-offline
  - serverless-plugin-typescript-express
service: serverless-weather-app
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: "build/app.server"
    events:
      - http:
          path: /
          method: GET
          cors: "true"
      - http:
          path: /weather
          method: GET
          cors: "true"
      - http:
          path: /about
          method: GET
          cors: "true"
      - http:
          path: /help
          method: GET
          cors: "true"
      - http:
          path: /help/{any+}
          method: GET
          cors: "true"
      - http:
          path: /products
          method: GET
          cors: "true"
      - http:
          path: /css/{any+}
          method: GET
          cors: "true"
      - http:
          path: /img/{any+}
          method: GET
          cors: "true"
      - http:
          path: /js/{any+}
          method: GET
          cors: "true"
      - http:
          path: /{proxy+}
          method: ANY
          cors: "true"
